---
layout: default
---

Lesson 1: Variables and Data Structures
==================

`r opts_chunk$set(cache=TRUE, cache.path="lesson1_cache/")`

Segment 1: Fundamentals
------------

```{r setup, echo=FALSE}
test1 = 2
test2 = 3
test3 = 4
```

```{r segment_1, dependson="setup", eval=FALSE}
# getwd()

# setwd("~/Desktop/lesson1")

ls()

rm(test1)

ls()

rm(list=ls())

ls()
```

Segment 2: Variables
------------

```{r segment_2}
my.number = 42

my.number

print(my.number)

chv1 = "hello"
chv2 = "world"

print(chv1)

6+4

x = 6+4
print(x)

y = 4
x / y

x^2
log(x)
```

Segment 3: Vectors
-----------

```{r segment_3, dependson="segment_2"}
v1 = c(1, 5.5, 1e2)
v2 = c(0.14, 0, -2)

v3 = c(v1, v2)
v3

v3[2]

v3[c(2, 3)]

v3_sub = v3[c(2, 3)]

v1 + 2
sin(v1)

sin(v1[2])
sin(v1)[2]

v1 * v2
v1
v2

v1 %*% v2

v1 %*% v3

length(v1)
length(v3)

chv2
chv2 + 10

class(v2)
class(chv2)

v4 = c("10", "42")
v4 / 10

v4 = as.numeric(v4)
class(v4)
v4 / 10

summary(v3)
summary(chv2)

mean(v3)
var(v3)
quantile(v3)
sum(v3)
median(v3)
sd(v3)
max(v3)
min(v3)

names(v3)
names(v2) = c("Cat", "Dog", "Rat")
v2
names(v2)
```

Segment 4: Matrix
---------------

```{r segment_4}
1:6

seq(from=1, to=12, by=4)

ma = matrix(1:6, nrow=3, ncol=2)
ma

mb = matrix(7:9, nrow=3, ncol=1)
mb

rbind(ma, c(100, 200))
m = cbind(ma, mb)
m

rbind(ma, mb)

m[1, 3]
m[1, 1:3]
m[1, ]
m[, 1:2]
m[5, ]

nrow(m)
ncol(m)
dim(m)

t(m)
m

diag(m)
diag(3)
diag(c(1,2,3))

m + 2
m * 2
m2 = matrix(21:32, nrow=3)
m3 = m %*% m2
```

Segment 5: Lists and Data Frames
-------------

```{r segment_5, dependson=c("segment_2", "segment_4")}
list(v1, chv2, ma)

my.list = list(numeric=v1, character=chv2, matrix=ma)

my.list[1]
class(my.list[1])

my.list[[1]]
class(my.list[[1]])

names(my.list)

my.list$matrix

class(my.list$matrix)

data(mtcars)
class(mtcars)

# ? mtcars

head(mtcars)

summary(mtcars)

names(mtcars)
colnames(mtcars)

mtcars$mpg
mtcars[, "mpg"]

mtcars[, 1]
mtcars[1:3, ]
```

Segment 6: Logical Vectors and Operators
-------------

```{r segment_6, dependson=c("segment_2", "segment_4")}
y = c(TRUE, FALSE, TRUE)
print(y)
class(y)

v2 > 0
m >= 5

mtcars$mpg > 20

v = mtcars$mpg > 20
efficient.cars = mtcars[v, ]
efficient.cars

efficient.cars = mtcars[mtcars$mpg > 20, ]

efficient.auto = mtcars[mtcars$mpg > 20 & mtcars$am == 0, ]
head(efficient.auto, 3)
```
