---
layout: default
---

Lesson 3: Statistical Testing and Prediction
===============

`r opts_chunk$set(cache=TRUE, cache.path="lesson3_cache/")`

<a name="segment1"></a>

Segment 1: Comparing Two Samples
--------------

```{r segment_1}
data("mtcars")

head(mtcars)

# help(mtcars)

mtcars$mpg

mtcars$am

library(ggplot2)

ggplot(mtcars, aes(x=factor(am), y=mpg)) + geom_boxplot()

ggplot(mtcars, aes(x=factor(am), y=mpg)) + geom_boxplot()

t.test(mpg ~ am, data=mtcars)

tt = t.test(mpg ~ am, data=mtcars)

tt$p.value

tt$conf.int

tt$conf.int[1]

tt$conf.int[2]
```

<a name="segment2"></a>

Segment 2: Correlation
--------------

```{r segment_2}
ggplot(mtcars, aes(x=wt, y=mpg)) + geom_point()

mtcars$mpg
mtcars$wt

cor.test(mtcars$mpg, mtcars$wt)

ct = cor.test(mtcars$mpg, mtcars$wt)

ct$p.value

ct$estimate

ct$conf.int
```

<a name="segment3"></a>

Segment 3: Linear Regression
-----------------

```{r segment_3}
fit = lm(mpg ~ wt, mtcars)

fit

summary(fit)

coef(summary(fit))

co = coef(summary(fit))
co[, 1]

co[, 4]

predict(fit)

summary(fit)

37.2851 + (-5.3445) * 4.5

newcar = data.frame(wt=4.5)

predict(fit, newcar)

ggplot(mtcars, aes(wt, mpg)) + geom_point() + geom_smooth(method="lm")
```

<a name="segment4"></a>

Segment 4: Multiple Linear Regression
-----------------

```{r segment_4}
ggplot(mtcars, aes(x=wt, y=mpg, col=cyl, size=disp)) + geom_point()

mfit = lm(mpg ~ wt + disp + cyl, mtcars)
summary(mfit)

mco = coef(summary(mfit))

mco[, 1]
mco[, 4]

predict(mfit)

newcar = data.frame(wt=4.5, disp=300, cyl=8)
newcar

predict(mfit, newcar)
```