---
layout: default
---

Lesson 4: Exploratory Data Analysis With data.table
===========

`r opts_chunk$set(cache=TRUE, cache.path="lesson4_cache/")`

<a name="segment1"></a>

Segment 1: R Scripts
-----------

```{r segment_1}
3 + 5

x = 4
y = x + 6

x
y
print(y)

library("ggplot2")
data(mtcars)
ggplot(mtcars, aes(wt, mpg)) + geom_point()

print(ggplot(mtcars, aes(wt, mpg)) + geom_point())
```

<a name="segment2"></a>

Segment 2: Reading Data
--------------

```{r segment_2}
data(mtcars)

# download Salaries.csv from
# http://dgrtwo.github.io/pages/lahman/Salaries.csv

salaries = read.csv("Salaries.csv")
head(salaries)

salaries = read.csv("http://dgrtwo.github.io/pages/lahman/Salaries.csv")
head(salaries)

# help(read.csv)
```

<a name="segment3"></a>

Segment 3: Introduction to data.table
-------------

```{r segment_3}
# install.packages("data.table")

library(data.table)
salaries = as.data.table(salaries)

salaries

head(salaries$salary)

salaries[1, ]
salaries[1:5, ]

head(salaries[, yearID])

salaries[, list(yearID, salary)]

salaries[yearID > 2000, ]

salaries[yearID == 2010, ]

salaries[lgID == "AL", ]

salaries[lgID == "AL" & yearID > 1990, ]

salaries[yearID > 2010 | yearID < 1990, ]

salaries[order(salary), ]

salaries[order(yearID, salary), ]

salaries.filtered = salaries[lgID == "AL" & yearID >= 1990, ]
salaries.filtered.sorted = salaries.filtered[order(salary), ]
```

<a name="segment4"></a>

Segment 4: Summarizing Data Within Groups
--------------

```{r segment_4, dependson="segment_3"}
head(salaries$salary)

mean(salaries$salary)

head(salaries[yearID == 2000, ]$salary)

mean(salaries[yearID == 2000, ]$salary)

summarized.year = salaries[, mean(salary), by="yearID"]
summarized.year

summarized.year = salaries[, list(Average=mean(salary)), by="yearID"]
summarized.year

summarized.year = salaries[, list(Average=mean(salary), Maximum=max(salary)), by="yearID"]
summarized.year

summarized.lg = salaries[, list(Average=mean(salary), Maximum=max(salary)), by="lgID"]
summarized.lg

summarized.team = salaries[, list(Average=mean(salary), Maximum=max(salary)), by="teamID"]
summarized.team

summarized.year[yearID > 2000, ]
summarized.team[order(Average), ]

summarized.year.lg = salaries[, list(Average=mean(salary), Maximum=max(salary)), by=c("yearID", "lgID")]
summarized.year.lg

summarized.year.team = salaries[, list(Average=mean(salary), Maximum=max(salary)), by=c("yearID", "teamID")]
summarized.year.team

library(ggplot2)
ggplot(salaries, aes(yearID, salary)) + geom_point()

summarized.year
ggplot(summarized.year, aes(yearID, Average)) + geom_line()

ggplot(summarized.year.lg, aes(yearID, Average, color=lgID)) + geom_line()
```

<a name="segment5"></a>

Segment 5: Merging Data
-------------

```{r segment_5, dependson="segment_3"}
master = read.csv("http://dgrtwo.github.io/pages/lahman/Master.csv")

master = as.data.table(master)

head(master)

salaries[playerID == "aardsda01"]

merged.salaries = merge(salaries, master, by="playerID")
merged.salaries[, name:=paste(nameFirst, nameLast)]

batting = read.csv("http://dgrtwo.github.io/pages/lahman/Batting.csv")
batting = as.data.table(batting)
batting

merged.batting = merge(batting, salaries, by=c("playerID", "teamID", "lgID", "yearID"))

merged.batting

merged.batting = merge(batting, salaries, by=c("playerID", "teamID", "lgID", "yearID"), all.x=TRUE)

merged.batting

merged.all = merge(merged.batting, master, by="playerID")
merged.all
```

<a name="segment6"></a>

Segment 6: Exploratory Data Analysis
-------------

```{r segment_6, dependson="segment_5"}
merged.all = merged.all[AB > 0]
merged.all

summarized.batters = merged.all[, list(Total.HR=sum(HR)), by="playerID"]
summarized.batters

merged.all[, name:=paste(nameFirst, nameLast)]
summarized.batters = merged.all[, list(Total.HR=sum(HR)), by=c("playerID", "name")]
summarized.batters

summarized.batters[order(Total.HR)]

summarized.batters = merged.all[, list(Total.HR=sum(HR), Total.R=sum(R), Total.H=sum(H)), by=c("playerID", "name")]
ggplot(summarized.batters, aes(Total.H, Total.R)) + geom_point()

189 / 602

summarized.batters = merged.all[, list(Total.HR=sum(HR), Total.R=sum(R), Total.H=sum(H), BattingAverage=sum(H) / sum(AB)), by=c("playerID", "name")]
summarized.batters

ggplot(summarized.batters, aes(BattingAverage)) + geom_histogram()
```